### ISSUE TITLE
Wider browser release

### ISSUE THREAD

**Issue by soapdog** [soapdog/patchfox#103]
This has been outlined originally in the new funding proposal of 2021: `%Y2iyBckEhcWvxX6a1+9ELeP6wFYD80QNdhvR50V1C7E=.sha256`.

> Wider browser release
> Patchfox now runs on Firefox, Chromium-based browsers, and Safari. Getting it to run is just half of the game, getting it to ship on these browsers extension store, and working out any browser-specific quirks is much harder.
>
> I’ll work to get Patchfox into the Chrome Web Store and Mac App Store (yes, Mac App Store, that’s where Safari Extensions live)

----

For this task to be completed, the following issues need to be closed:

* [x] #97 - Ship Patchfox for Google Chrome.
* [x] #98 - Ship Patchfox for Brave Browser.
* [x] #99 - Ship Patchfox for Microsoft Edge.
* [x] #100 - Ship Patchfox for Vivaldi.
* ❌ #101 - Ship Patchfox for Opera.
* ❌ #102 - Ship Patchfox for Safari.

**Comment by Ryuno-Ki** [comment]
Some of these got already closed and could be checked, I think.

**Comment by soapdog** [comment]
Just checked them. I don't know why I had the impression that that would happen automagically :D

**Comment by soapdog** [comment]
Be aware that release for Opera and Safari are _Tier 3_ priorities, and other issues will be worked out before them.

**Comment by soapdog** [comment]
Closing the issues for Safari and Opera as I can't implement them at the moment. Safari requires too many changes and Opera is not answering.
