### ISSUE TITLE
refactor app launching to account for multiple identities

### ISSUE THREAD

**Issue by soapdog** [soapdog/patchfox#108]
Once issues

* [ ] #105 - improve `nodejs-ssb` platform.
* [ ] #106 - create mechanisms for packages to support platforms.
* [ ] #107 - settings refactor to support multiple identities.

Are all in place, Patchfox will have the correct groundwork to establish connections to different servers/identity combinations for each browser tab.

The add-on initialization in `index.html` assumes `nodejs-ssb` platform as a _global_ under `window.ssb.*`. This needs to change so that new tabs can specify what platform and identity should be used for its initialization.
